language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3'
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - flake8 setup.py test.py genderize
  - nosetests --with-coverage --cover-package genderize
deploy:
  provider: pypi
  user: SteelPangolin
  password:
    secure: ESeqX6NhNQmNUOFwy5YS3JyZIQqL83zKTd69boBinjnOP8VfL/STfwN0/ZXTQE5+agJDoKN3jlLTbxYi8bgyp8GwD3P8nylg0Lx8VbjemOQcpSQ9zeRpIKGvz9EG50nWR+7vGJQIKsb5hWJDNtcPnYIDY/2tr/kFUzCG3jz6a0Y=
  on:
    python: '3.6'
    tags: true
    repo: SteelPangolin/genderize
  distributions: "sdist bdist_wheel"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -X POST https://readthedocs.org/build/genderize
