language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 genderize
  - nosetests
deploy:
  provider: pypi
  user: SteelPangolin
  password:
    secure: ESeqX6NhNQmNUOFwy5YS3JyZIQqL83zKTd69boBinjnOP8VfL/STfwN0/ZXTQE5+agJDoKN3jlLTbxYi8bgyp8GwD3P8nylg0Lx8VbjemOQcpSQ9zeRpIKGvz9EG50nWR+7vGJQIKsb5hWJDNtcPnYIDY/2tr/kFUzCG3jz6a0Y=
  on:
    tags: true
    repo: SteelPangolin/genderize
  distributions: "sdist bdist_wheel"
after_success:
  - curl -X POST https://readthedocs.org/build/genderize
